export const DEFAULT_COUNTRY_DIAL = '57';

export interface CountryCode {
  name: string;
  dial: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { dial: '93', name: 'Afganistán' },
  { dial: '355', name: 'Albania' },
  { dial: '49', name: 'Alemania' },
  { dial: '376', name: 'Andorra' },
  { dial: '244', name: 'Angola' },
  { dial: '1264', name: 'Anguila' },
  { dial: '672', name: 'Antártida' },
  { dial: '1268', name: 'Antigua y Barbuda' },
  { dial: '966', name: 'Arabia Saudita' },
  { dial: '213', name: 'Argelia' },
  { dial: '54', name: 'Argentina' },
  { dial: '374', name: 'Armenia' },
  { dial: '297', name: 'Aruba' },
  { dial: '61', name: 'Australia' },
  { dial: '43', name: 'Austria' },
  { dial: '994', name: 'Azerbaiyán' },
  { dial: '1242', name: 'Bahamas' },
  { dial: '973', name: 'Baréin' },
  { dial: '880', name: 'Bangladés' },
  { dial: '1246', name: 'Barbados' },
  { dial: '32', name: 'Bélgica' },
  { dial: '501', name: 'Belice' },
  { dial: '229', name: 'Benín' },
  { dial: '375', name: 'Bielorrusia' },
  { dial: '591', name: 'Bolivia' },
  { dial: '387', name: 'Bosnia y Herzegovina' },
  { dial: '267', name: 'Botsuana' },
  { dial: '55', name: 'Brasil' },
  { dial: '673', name: 'Brunéi' },
  { dial: '359', name: 'Bulgaria' },
  { dial: '226', name: 'Burkina Faso' },
  { dial: '257', name: 'Burundi' },
  { dial: '975', name: 'Bután' },
  { dial: '238', name: 'Cabo Verde' },
  { dial: '855', name: 'Camboya' },
  { dial: '237', name: 'Camerún' },
  { dial: '1', name: 'Canadá' },
  { dial: '599', name: 'Caribe Neerlandés' },
  { dial: '974', name: 'Catar' },
  { dial: '235', name: 'Chad' },
  { dial: '56', name: 'Chile' },
  { dial: '86', name: 'China' },
  { dial: '357', name: 'Chipre' },
  { dial: '57', name: 'Colombia' },
  { dial: '269', name: 'Comoras' },
  { dial: '242', name: 'Congo' },
  { dial: '850', name: 'Corea del Norte' },
  { dial: '82', name: 'Corea del Sur' },
  { dial: '225', name: 'Costa de Marfil' },
  { dial: '506', name: 'Costa Rica' },
  { dial: '385', name: 'Croacia' },
  { dial: '53', name: 'Cuba' },
  { dial: '599', name: 'Curazao' },
  { dial: '45', name: 'Dinamarca' },
  { dial: '1767', name: 'Dominica' },
  { dial: '593', name: 'Ecuador' },
  { dial: '20', name: 'Egipto' },
  { dial: '503', name: 'El Salvador' },
  { dial: '971', name: 'Emiratos Árabes Unidos' },
  { dial: '291', name: 'Eritrea' },
  { dial: '421', name: 'Eslovaquia' },
  { dial: '386', name: 'Eslovenia' },
  { dial: '34', name: 'España' },
  { dial: '1', name: 'Estados Unidos' },
  { dial: '372', name: 'Estonia' },
  { dial: '268', name: 'Esuatini' },
  { dial: '251', name: 'Etiopía' },
  { dial: '63', name: 'Filipinas' },
  { dial: '358', name: 'Finlandia' },
  { dial: '679', name: 'Fiyi' },
  { dial: '33', name: 'Francia' },
  { dial: '241', name: 'Gabón' },
  { dial: '220', name: 'Gambia' },
  { dial: '995', name: 'Georgia' },
  { dial: '233', name: 'Ghana' },
  { dial: '350', name: 'Gibraltar' },
  { dial: '1473', name: 'Granada' },
  { dial: '30', name: 'Grecia' },
  { dial: '299', name: 'Groenlandia' },
  { dial: '590', name: 'Guadalupe' },
  { dial: '1671', name: 'Guam' },
  { dial: '502', name: 'Guatemala' },
  { dial: '594', name: 'Guayana Francesa' },
  { dial: '44', name: 'Guernsey' },
  { dial: '224', name: 'Guinea' },
  { dial: '245', name: 'Guinea-Bisáu' },
  { dial: '240', name: 'Guinea Ecuatorial' },
  { dial: '592', name: 'Guyana' },
  { dial: '509', name: 'Haití' },
  { dial: '504', name: 'Honduras' },
  { dial: '852', name: 'Hong Kong' },
  { dial: '36', name: 'Hungría' },
  { dial: '91', name: 'India' },
  { dial: '62', name: 'Indonesia' },
  { dial: '964', name: 'Irak' },
  { dial: '98', name: 'Irán' },
  { dial: '353', name: 'Irlanda' },
  { dial: '44', name: 'Isla de Man' },
  { dial: '354', name: 'Islandia' },
  { dial: '1345', name: 'Islas Caimán' },
  { dial: '682', name: 'Islas Cook' },
  { dial: '298', name: 'Islas Feroe' },
  { dial: '500', name: 'Islas Malvinas' },
  { dial: '1670', name: 'Islas Marianas del Norte' },
  { dial: '692', name: 'Islas Marshall' },
  { dial: '677', name: 'Islas Salomón' },
  { dial: '1649', name: 'Islas Turcas y Caicos' },
  { dial: '1284', name: 'Islas Vírgenes Británicas' },
  { dial: '1340', name: 'Islas Vírgenes de EE.UU.' },
  { dial: '972', name: 'Israel' },
  { dial: '39', name: 'Italia' },
  { dial: '1876', name: 'Jamaica' },
  { dial: '81', name: 'Japón' },
  { dial: '44', name: 'Jersey' },
  { dial: '962', name: 'Jordania' },
  { dial: '7', name: 'Kazajistán' },
  { dial: '254', name: 'Kenia' },
  { dial: '996', name: 'Kirguistán' },
  { dial: '686', name: 'Kiribati' },
  { dial: '383', name: 'Kosovo' },
  { dial: '965', name: 'Kuwait' },
  { dial: '856', name: 'Laos' },
  { dial: '266', name: 'Lesoto' },
  { dial: '371', name: 'Letonia' },
  { dial: '961', name: 'Líbano' },
  { dial: '231', name: 'Liberia' },
  { dial: '218', name: 'Libia' },
  { dial: '423', name: 'Liechtenstein' },
  { dial: '370', name: 'Lituania' },
  { dial: '352', name: 'Luxemburgo' },
  { dial: '853', name: 'Macao' },
  { dial: '389', name: 'Macedonia del Norte' },
  { dial: '261', name: 'Madagascar' },
  { dial: '60', name: 'Malasia' },
  { dial: '265', name: 'Malaví' },
  { dial: '960', name: 'Maldivas' },
  { dial: '223', name: 'Malí' },
  { dial: '356', name: 'Malta' },
  { dial: '212', name: 'Marruecos' },
  { dial: '596', name: 'Martinica' },
  { dial: '230', name: 'Mauricio' },
  { dial: '222', name: 'Mauritania' },
  { dial: '52', name: 'México' },
  { dial: '691', name: 'Micronesia' },
  { dial: '373', name: 'Moldavia' },
  { dial: '377', name: 'Mónaco' },
  { dial: '976', name: 'Mongolia' },
  { dial: '382', name: 'Montenegro' },
  { dial: '258', name: 'Mozambique' },
  { dial: '95', name: 'Myanmar' },
  { dial: '264', name: 'Namibia' },
  { dial: '674', name: 'Nauru' },
  { dial: '977', name: 'Nepal' },
  { dial: '505', name: 'Nicaragua' },
  { dial: '227', name: 'Níger' },
  { dial: '234', name: 'Nigeria' },
  { dial: '47', name: 'Noruega' },
  { dial: '687', name: 'Nueva Caledonia' },
  { dial: '64', name: 'Nueva Zelanda' },
  { dial: '968', name: 'Omán' },
  { dial: '31', name: 'Países Bajos' },
  { dial: '92', name: 'Pakistán' },
  { dial: '680', name: 'Palaos' },
  { dial: '970', name: 'Palestina' },
  { dial: '507', name: 'Panamá' },
  { dial: '675', name: 'Papúa Nueva Guinea' },
  { dial: '595', name: 'Paraguay' },
  { dial: '51', name: 'Perú' },
  { dial: '689', name: 'Polinesia Francesa' },
  { dial: '48', name: 'Polonia' },
  { dial: '351', name: 'Portugal' },
  { dial: '1', name: 'Puerto Rico' },
  { dial: '44', name: 'Reino Unido' },
  { dial: '236', name: 'República Centroafricana' },
  { dial: '420', name: 'República Checa' },
  { dial: '1', name: 'República Dominicana' },
  { dial: '250', name: 'Ruanda' },
  { dial: '40', name: 'Rumania' },
  { dial: '7', name: 'Rusia' },
  { dial: '212', name: 'Sáhara Occidental' },
  { dial: '685', name: 'Samoa' },
  { dial: '1684', name: 'Samoa Americana' },
  { dial: '590', name: 'San Bartolomé' },
  { dial: '1869', name: 'San Cristóbal y Nieves' },
  { dial: '378', name: 'San Marino' },
  { dial: '590', name: 'San Martín' },
  { dial: '508', name: 'San Pedro y Miquelón' },
  { dial: '1784', name: 'San Vicente y las Granadinas' },
  { dial: '1758', name: 'Santa Lucía' },
  { dial: '239', name: 'Santo Tomé y Príncipe' },
  { dial: '221', name: 'Senegal' },
  { dial: '381', name: 'Serbia' },
  { dial: '248', name: 'Seychelles' },
  { dial: '232', name: 'Sierra Leona' },
  { dial: '65', name: 'Singapur' },
  { dial: '963', name: 'Siria' },
  { dial: '252', name: 'Somalia' },
  { dial: '94', name: 'Sri Lanka' },
  { dial: '27', name: 'Sudáfrica' },
  { dial: '249', name: 'Sudán' },
  { dial: '211', name: 'Sudán del Sur' },
  { dial: '46', name: 'Suecia' },
  { dial: '41', name: 'Suiza' },
  { dial: '597', name: 'Surinam' },
  { dial: '66', name: 'Tailandia' },
  { dial: '886', name: 'Taiwán' },
  { dial: '255', name: 'Tanzania' },
  { dial: '992', name: 'Tayikistán' },
  { dial: '670', name: 'Timor Oriental' },
  { dial: '228', name: 'Togo' },
  { dial: '676', name: 'Tonga' },
  { dial: '1868', name: 'Trinidad y Tobago' },
  { dial: '216', name: 'Túnez' },
  { dial: '993', name: 'Turkmenistán' },
  { dial: '90', name: 'Turquía' },
  { dial: '688', name: 'Tuvalu' },
  { dial: '380', name: 'Ucrania' },
  { dial: '256', name: 'Uganda' },
  { dial: '598', name: 'Uruguay' },
  { dial: '998', name: 'Uzbekistán' },
  { dial: '678', name: 'Vanuatu' },
  { dial: '39', name: 'Ciudad del Vaticano' },
  { dial: '58', name: 'Venezuela' },
  { dial: '84', name: 'Vietnam' },
  { dial: '967', name: 'Yemen' },
  { dial: '253', name: 'Yibuti' },
  { dial: '260', name: 'Zambia' },
  { dial: '263', name: 'Zimbabue' },
].sort((a, b) => a.name.localeCompare(b.name, 'es'));

const DIAL_CODES_DESC = [...new Set(COUNTRY_CODES.map((c) => c.dial))].sort(
  (a, b) => b.length - a.length
);

export function parseRecipientPhone(full: string): { dial: string; number: string } {
  const digits = full.replace(/\D/g, '');
  if (!digits) return { dial: DEFAULT_COUNTRY_DIAL, number: '' };

  for (const dial of DIAL_CODES_DESC) {
    if (digits.startsWith(dial)) {
      return { dial, number: digits.slice(dial.length) };
    }
  }

  return { dial: DEFAULT_COUNTRY_DIAL, number: digits };
}

export function buildRecipientPhone(dial: string, number: string): string {
  const local = number.replace(/\D/g, '');
  return `${dial.replace(/\D/g, '')}${local}`;
}
